eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
feign:
  circuitbreaker:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,refresh'
spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  data:
    mongodb:
      database: customer-db
      host: localhost
      port: 27017