feign:
  circuitbreaker:
    enabled: true
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,refresh'
spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  data:
    mongodb:
      database: customer-db
      host: ${SPRING_DATA_MONGODB_HOST:mongo-db}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
