feign:
  circuitbreaker:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,refresh'
spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  data:
    mongodb:
      database: customer-db
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
