spring:
  cloud:
    gateway:
      routes:
        - id: customerService
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api(?<segment>/.*), $\{segment}
          order: 0
        - id: orderService
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=/api(?<segment>/.*), $\{segment}
          order: 5
        - id: orderManagingService
          uri: lb://order-managing-service
          predicates:
            - Path=/api/orders
            - Method=POST
          filters:
            - RewritePath=/api(?<segment>/.*), $\{segment}
          order: 0
eureka:
  client:
    enabled: true
    registerWithEureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
    
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health,info,refresh,gateway'
