management:
  endpoints:
    web:
      exposure:
        include: 'health,info,refresh'

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-service:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: orderinfo:com.sampleservices.ordermanagingservice.model.OrderInfo
