eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,refresh'
spring:
  data:
    mongodb:
      database: order-db
      host: localhost
      port: 27017
